# Generated by Django 3.2.2 on 2021-06-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_Subjects',
            fields=[
                ('MAMH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_management_app.subjects')),
                ('GiaTC', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PHIEUDK_DAY',
            fields=[
                ('MAGV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_management_app.staffs')),
                ('tongmonday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='THUCHANH',
            fields=[
                ('MATH', models.AutoField(primary_key=True, serialize=False)),
                ('soTietTH', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
        migrations.AddField(
            model_name='staffs',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='ID_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='nienkhoa',
            field=models.CharField(default=2018, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='so_tc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='tongsvdk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Staff_GV')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Time_subject',
            fields=[
                ('ID_time', models.AutoField(primary_key=True, serialize=False)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('Mahocki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_exam_marks', models.FloatField(default=0)),
                ('subject_assignment_marks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Staffs_GV_HP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.FileField(null=True, upload_to='')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PHONGHOC',
            fields=[
                ('MAPHONG', models.AutoField(primary_key=True, serialize=False)),
                ('BUOIHOC', models.CharField(max_length=20)),
                ('Thu', models.CharField(max_length=20)),
                ('Siso_phong', models.IntegerField()),
                ('MAGVCAPPHONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs_gv_hp')),
                ('MAMH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
            ],
            options={
                'unique_together': {('MAPHONG', 'BUOIHOC', 'Thu', 'MAMH')},
            },
        ),
        migrations.CreateModel(
            name='PHIEUDK_HOCPHAN',
            fields=[
                ('MASV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_management_app.students')),
                ('MAPHONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.phonghoc')),
            ],
        ),
        migrations.CreateModel(
            name='Nhom_TH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startday_TH', models.DateField(auto_now_add=True)),
                ('endday_TH', models.DateField(auto_now=True)),
                ('name_nhom', models.CharField(max_length=20)),
                ('MATH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.thuchanh')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_phieudkday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAMODAY', models.CharField(max_length=50)),
                ('MAGV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='MAGV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.phieudk_day'),
            preserve_default=False,
        ),
    ]
