# Generated by Django 3.2.2 on 2021-06-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210614_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs_gv_hp',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
