# Generated by Django 3.2.2 on 2021-06-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20210612_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
