# Generated by Django 3.2.2 on 2021-06-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_staffs_gv_hp_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='MATH',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.thuchanh'),
            preserve_default=False,
        ),
    ]
