# Generated by Django 3.2.2 on 2021-06-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_feedbackstaffs_gv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Staffs_GV_HP')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs_gv',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs_gv_hp'),
        ),
    ]
