# Generated by Django 3.2.2 on 2021-06-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210608_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
