# Generated by Django 3.2.2 on 2021-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_alter_staffs_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='so_tc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='tongsvdk',
            field=models.IntegerField(null=True),
        ),
    ]
