# Generated by Django 3.2.2 on 2021-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_nhom_th_startday_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhom_th',
            name='startday_TH',
            field=models.DateField(),
        ),
    ]
