# Generated by Django 3.2.2 on 2021-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_nhom_th_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_phieudkday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
